# Generated by Django 3.1.2 on 2020-10-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommend',
            options={'managed': False},
        ),
    ]
